micronaut:
  application:
    name: petservice
  server:
    port: 9000
#mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
mongodb.uri: mongodb+srv://pets:qwartz@cluster0.yb3tc.mongodb.net/pets-adopts?retryWrites=true&w=majority
