micronaut:
  application:
    name: pet-service

  server:
    port: 9000

mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017/pet_db}
  max: 50

#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
